import React from 'react'
import './style.scss'
import Logo from '../../assets/logo-fakebook.svg'
import { useContext } from 'react'
import { contextUser } from '../context/UserContext'

const SingleMessage = ({user, setChatUserId}) => {
  const {userInbox} = useContext(contextUser);
  
  return (
    <div className='singlemessage-container'>

        <div className="user-container" onClick={() =>{
          userInbox();
          setChatUserId(user._id)
        }}>
          <img src={`data:image/svg+xml;base64,${user.avatarImage}`} alt="may be the image of user which is generated by ai" />
          <div className="user-message">
            <h3>{user.username}</h3>
            <p>k xa babu temro </p>
          </div>
          
           </div>

    </div>
  )
}

export default SingleMessage
